# Generated by Django 5.0.1 on 2024-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeProblem',
            fields=[
                ('problem_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experience_points', models.IntegerField(verbose_name='points awarder for completing the problem')),
            ],
        ),
    ]
