# Generated by Django 5.0.1 on 2024-03-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeproblem',
            name='problem_difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='EASY', max_length=6),
        ),
        migrations.AddField(
            model_name='codeproblem',
            name='programming_languages',
            field=models.CharField(choices=[('JAVA', 'Java'), ('PYTHON', 'Python'), ('C++', 'Cpp')], default='', max_length=20),
        ),
    ]
