# Generated by Django 5.0.1 on 2024-03-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_codeproblem_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproblem',
            name='experience_points',
            field=models.IntegerField(),
        ),
    ]
