# Generated by Django 5.0.1 on 2024-03-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_codeproblem_experience_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproblem',
            name='programming_languages',
            field=models.CharField(choices=[('JAVA', 'JAVA'), ('PYTHON', 'PYTHON'), ('CPP', 'C++')], default='PYTHON', max_length=20),
        ),
    ]
