# Generated by Django 5.0.1 on 2024-03-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_alter_codeproblem_programming_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproblem',
            name='problem_difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='EASY', max_length=6),
        ),
        migrations.AlterField(
            model_name='codeproblem',
            name='programming_languages',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C++', 'Cpp')], default='', max_length=20),
        ),
    ]
