# Generated by Django 5.0.1 on 2024-03-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_alter_codeproblem_problem_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproblem',
            name='problem_difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=6),
        ),
    ]
