# Generated by Django 5.0.1 on 2024-03-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_codeproblem_problem_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeproblem',
            old_name='problem_difficulty',
            new_name='difficulty',
        ),
        migrations.RenameField(
            model_name='codeproblem',
            old_name='programming_languages',
            new_name='languages',
        ),
    ]
