# Generated by Django 5.0.1 on 2024-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_rename_problem_difficulty_codeproblem_difficulty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeproblem',
            name='languages',
            field=models.CharField(choices=[('Java', 'Java'), ('Python', 'Python'), ('C', 'C'), ('C++', 'Cpp')], default='', max_length=20),
        ),
    ]
