# Generated by Django 5.0.1 on 2024-03-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertolang',
            name='language',
        ),
        migrations.RemoveField(
            model_name='problemtolang',
            name='language',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='usertoproblem',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='problemtolang',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='usertoproblem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertolang',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
        migrations.DeleteModel(
            name='CodingLanguage',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='ProblemToLang',
        ),
        migrations.DeleteModel(
            name='UserToProblem',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserToLang',
        ),
    ]
