# Generated by Django 5.0.1 on 2024-03-15 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg_id', models.IntegerField(blank=True, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('origin_of_msg', models.IntegerField(blank=True, null=True)),
                ('mentee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.user')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='chatroom_mentor_set', to='base.user')),
            ],
            options={
                'db_table': 'chatroom',
                'managed': True,
            },
        ),
    ]
