# Generated by Django 5.0.1 on 2024-03-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingLanguage',
            fields=[
                ('language_id', models.TextField(primary_key=True, serialize=False)),
                ('language_name', models.TextField()),
            ],
            options={
                'db_table': 'coding_language',
                'managed': True,
            },
        ),
    ]
