# Generated by Django 5.0.1 on 2024-03-15 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_usertolang'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user')),
            ],
            options={
                'db_table': 'user_to_problem',
                'managed': True,
            },
        ),
    ]
