# Generated by Django 5.0.1 on 2024-03-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_user_date_joined'),
        ('base', '0014_topics_alter_user_date_joined_problemtotopic'),
    ]

    operations = [
    ]
