# Generated by Django 5.0.1 on 2024-04-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_topics_alter_user_date_joined_problemtotopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='exp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
