# Generated by Django 5.0.1 on 2024-04-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_merge_20240320_1257'),
        ('base', '0015_problem_exp'),
    ]

    operations = [
    ]
