# Generated by Django 5.0.1 on 2024-04-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_merge_0015_merge_20240320_1257_0015_problem_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoproblem',
            name='language_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.codinglanguage'),
        ),
    ]
