# Generated by Django 5.0.1 on 2024-04-18 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_usertoproblem_language_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoproblem',
            old_name='language_id',
            new_name='language',
        ),
    ]
